import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import houseImage from '../public/main_home.jpg'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import { FaPlay } from "react-icons/fa"
import { BiGlobe } from "react-icons/bi";
import { IoIosArrowUp } from "react-icons/io";

/* const graphcms = new GraphQLClient('https://api-us-west-2.graphcms.com/v2/cl51ze6181wt601ukbse59thb/master')

const QUERY = gql`
{
  properties {
    street_address,
    city,
    state,
    zip_code
  }
}
`

export async function getStaticProps() {
  const {properties} = await graphcms.request(QUERY)
  return{
    props: {
      properties,
    },
    revalidate: 10,
  }
} */



export async function getStaticProps() {
  const url = process.env.GRAPH_CMS_ENDPOINT
  const Client = new GraphQLClient(url, {
    headers: {
      "Authorization" : process.env.GRAPH_CMS_TOKEN
    }
  })
  const QUERY = gql`
  {
    properties {
      street_address,
      city,
      state,
      zip_code
    }
  }
  `
const data = await Client.request(QUERY)
const properties = data.properties

return{
  props: {
    properties
  }
}
}




export default function Home({properties}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moonstone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
{/*         <h1>Properties:</h1>
        {properties.map((property) => (
          <h1>{property.street_address} {property.city}, {property.zip_code}</h1>
        ))} */}

        <div className={styles.headerContainer}>
          <div className={styles.headerInnerContainer}>
            <div className={styles.contentContainer}>MOSAIC</div>
            <div className={styles.centerContentContainer}>
              <p className={styles.p}>Learn More</p>
              <p className={styles.p}>Why Mosaic</p>
              <p className={styles.p}>Tools</p>
            </div>
            <div className={styles.contentContainer}>
              <Link href="/signin">
                <a>
                  <p className={styles.p}>Log in</p>
                </a>
              </Link>
              <Link href="/signup">
                <a>
                  <button className={styles.button}>Sign up</button>
                </a>
              </Link>
              
            </div>
          </div>
        </div>
{/*         MAIN BODY */}
        <div className={styles.mainBodyContainer}>
          <div className={styles.mainBodyInnerContainer}>
            <div className={styles.containerLeft}>
              <h1 className={styles.h1}>A Platform to Manage and Track<br/>Real Estate Portfolios at Scale</h1>
              <h2 className={styles.h2}>Real estate professiols use this platform to do the things<br/>that make them make more money and more money<br/>is more money</h2>
              <button className={styles.getStarted}>Get Started</button>
{/*               <p className={styles.small}>Completely free, forever</p>
              <p className={styles.small}>No CC required</p> */}
            </div>
            <div className={styles.containerRight}>
              <div className={styles.mainImage}>
              <Image
                      alt={`A frame house in the mountains`}
                      src={houseImage}
                      layout={`responsive`}
                    />
              </div>
              <div className={styles.displayContainersRight}>
                <div className={styles.factContainer}>
                  <p className={styles.pHeader}>Ownership</p>
                  <p className={styles.pMetric}>25%</p>
                  <p className={styles.pMetric}>6 <span className={styles.span}>Partners</span></p>
                </div>
                <div className={styles.factContainer}>
                  <p className={styles.pHeader}>Maintenance</p>
                  <p className={styles.pMetric}>3 <span className={styles.span}>open</span></p>
                  <p className={styles.pMetric}>0 <span className={styles.span}>critical</span></p>
                </div>
                <div className={styles.factContainer}>
                  <p className={styles.pHeader}>Expenses</p>
                  <p className={styles.pMetric}>$830</p>
                  <p className={styles.span}>Down 12% M/M</p>
                </div>
                <div className={styles.factContainer}>
                  <p className={styles.pHeader}>August</p>
                  <p className={styles.pHeader}>Cash Flow</p>
                  <p className={styles.pMetric}>$2,100</p>
                </div>
                <div className={styles.factContainer}>
                  <p className={styles.pHeader}>Equity</p>
                  <p className={styles.pMetric}>$615.2K</p>
                  <p className={styles.span}>Up 1% M/M</p>
                </div>
              </div>

            </div>
          </div>
        </div>
        {/* MAIN BODY END AND FEATURE CALLOUTS BEGIN */}
        <div className={styles.featureHeader}>
          <p className={styles.featureText}>Mosaic in 90 seconds</p>
        </div>
        <div className={styles.videoContainer}>
          <div className={styles.videoPlayer}>
            <FaPlay className={styles.playButton}/>
          </div>
        </div>
        {/* VIDEO PLAYER END */}
        <div className={styles.featureContainer}>
          <div className={styles.featureInnerContainer}>
            
            <div className={styles.calloutContainer}>
              <div className={styles.calloutLeft}>
                <h4 className={styles.calloutHeader}>This is a header</h4>
                <p className={styles.calloutText}>This is a paragraph look at me doing paragraph things.</p>
              </div>
              <div className={styles.calloutRight}></div>
            </div>

            <div className={styles.calloutContainer}>
              <div className={styles.calloutLeft}>
                <h4 className={styles.calloutHeader}>This is a header</h4>
                <p className={styles.calloutText}>This is a paragraph look at me doing paragraph things.</p>
              </div>
              <div className={styles.calloutRight}></div>
            </div>

            <div className={styles.calloutContainer}>
              <div className={styles.calloutLeft}>
                <h4 className={styles.calloutHeader}>This is a header</h4>
                <p className={styles.calloutText}>This is a paragraph look at me doing paragraph things.</p>
              </div>
              <div className={styles.calloutRight}></div>
            </div>

            <div className={styles.calloutContainer}>
              <div className={styles.calloutLeft}>
                <h4 className={styles.calloutHeader}>This is a header</h4>
                <p className={styles.calloutText}>This is a paragraph look at me doing paragraph things.</p>
              </div>
              <div className={styles.calloutRight}></div>
            </div>

          </div>
        </div>
        {/* FEATURE SECTION END FOOT BEGIN */}
        <div className={styles.footer}>
                <div className={styles.innerFooterContainer}>
                    <div className={styles.innerFooterOne}>
                        <p className={styles.pLeft}>© Mosaic, Inc.</p>
                        <p className={styles.pLeft}>Privacy</p>
                        <p className={styles.pLeft}>Terms</p>
                        <p className={styles.pLeft}>Sitemap</p>
                        <p className={styles.pLeft}>Contact</p>
                    </div>
                    <div className={styles.innerFooterTwo}>
                        <BiGlobe />
                        <p className={styles.pRight}>English</p>
                        <p className={styles.pRight}>Support & Resources</p>
                        <IoIosArrowUp />
                    </div>
                </div>
            </div>
        {/* FOOTER MODAL */}
        {/* <div className={styles.footerModalContainer}></div> */}
      </main>
    </div>
  )
}
