import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request' 

/* const graphcms = new GraphQLClient('https://api-us-west-2.graphcms.com/v2/cl51ze6181wt601ukbse59thb/master')

const QUERY = gql`
{
  properties {
    street_address,
    city,
    state,
    zip_code
  }
}
`

export async function getStaticProps() {
  const {properties} = await graphcms.request(QUERY)
  return{
    props: {
      properties,
    },
    revalidate: 10,
  }
} */



export async function getStaticProps() {
  const url = process.env.GRAPH_CMS_ENDPOINT
  const Client = new GraphQLClient(url, {
    headers: {
      "Authorization" : process.env.GRAPH_CMS_TOKEN
    }
  })
  const QUERY = gql`
  {
    properties {
      street_address,
      city,
      state,
      zip_code
    }
  }
  `
const data = await Client.request(QUERY)
const properties = data.properties

return{
  props: {
    properties
  }
}
}




export default function Home({properties}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moonstone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Properties:</h1>
        {properties.map((property) => (
          <h1>{property.street_address}, {property.city}</h1>
        ))}
      </main>
    </div>
  )
}
